---
# SPDX-License-Identifier: EUPL-1.2
# yamllint disable-line rule:line-length
# SPDX-FileCopyrightText: 2025-present J√ºrgen M√ºlbert <juergen.muelbert@outlook.de>

name: Documentation Deployment
# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    paths:
      - docs/**
      - CHANGELOG.md
      - .github/CONTRIBUTING.md
      - .github/CODE_OF_CONDUCT.md
      - mkdocs.yml
      - .github/workflows/docs-deploy.yml
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # For pushing to the gh-pages branch
      pages: write # Required for deploying to GitHub Pages
      id-token: write # Required for OIDC authentication with GitHub Page

    steps:
      - name: üîí Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a  # v2.13.1
        with:
          egress-policy: audit

      - name: üß∞ Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: üîß Call Python Environment Setup
        uses: ./.github/actions/python-setup
        id: python-setup

      - name: üìù Get Project Version and Deploy Docs
        # This single step combines both actions for efficiency
        run: |
          VERSION=$(hatch version)
          # Use `hatch env run` to execute mike within the docs environment
          hatch env run --env docs -- mike deploy --push --update-aliases "${VERSION}"

  verify:
    needs: [build-and-deploy]
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: üîí Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a  # v2.13.1
        with:
          egress-policy: audit
      - name: ‚úÖ Verify Workflow Completion
        uses: re-actors/alls-green@223e4bb7a751b91f43eda76992bcfbf23b8b0302  # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
